"""empty message

Revision ID: 0a2989e21fc5
Revises: ddf496359867
Create Date: 2024-11-05 21:51:43.010916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2989e21fc5'
down_revision: Union[str, None] = 'ddf496359867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('demolition_timestamp', sa.BigInteger(), nullable=True))
    op.drop_column('users', 'next_demolition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('next_demolition', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'demolition_timestamp')
    # ### end Alembic commands ###
