"""Init

Revision ID: 78b59a6d6452
Revises: 
Create Date: 2024-10-29 19:19:32.348163

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78b59a6d6452'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admins',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
        sa.UniqueConstraint('id', name=op.f('uq_admins_id')),
        schema='public',
    )
    op.create_index(op.f('ix_public_admins_user_id'), 'admins', ['user_id'], unique=True, schema='public')
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subscription', sa.BigInteger(), nullable=True),
        sa.Column('waiting_invoice', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('id', name=op.f('uq_users_id')),
        schema='public',
    )
    op.create_index(op.f('ix_public_users_user_id'), 'users', ['user_id'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_user_id'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_admins_user_id'), table_name='admins', schema='public')
    op.drop_table('admins', schema='public')
    # ### end Alembic commands ###
